name = "ExamplePkg"
uuid = "1dd05a55-6ff6-40d9-9121-e2ac7b973bf5"
authors = ["Victor Liu <victorliu1231@gmail.com>"]
version = "0.1.0"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Distributions = "0.25.122"
Test = "1.11.0"
